redis:
  host: 'localhost'
  port: 6380
  prefix: 'ElyPool:Statistics:PointsInTime:'
  enabled: = True

load_data:
  past_days: 10

filters:
  kolizeum: 3

prediction:
  number_of_cicles: 1
  freq: '10min'
